<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-tachometer-alt',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-users',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-ribbon',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-construct',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-pulse',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 10,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-database',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 11,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 12,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-attach',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas ion-ios-cog',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2019-10-25 07:19:44',
                'updated_at' => '2019-10-25 07:19:44',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Galleries',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2019-10-25 08:42:45',
                'updated_at' => '2019-10-25 08:42:45',
                'route' => 'voyager.galleries.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Services',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'ion-ios-basket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2019-10-25 11:06:47',
                'updated_at' => '2019-10-25 11:06:47',
                'route' => 'voyager.services.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pay Options',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'ion-ios-card',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2019-10-25 11:08:01',
                'updated_at' => '2019-10-25 11:08:01',
                'route' => 'voyager.pay-options.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Responds',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2019-10-25 11:09:29',
                'updated_at' => '2019-10-25 11:09:29',
                'route' => 'voyager.responds.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Coupons',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2019-10-25 11:09:42',
                'updated_at' => '2019-10-25 11:09:42',
                'route' => 'voyager.coupons.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Class Events',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'ion-ios-calendar',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2019-10-25 11:56:02',
                'updated_at' => '2019-10-25 11:56:02',
                'route' => 'voyager.class-events.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Bookings',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2019-10-25 12:37:28',
                'updated_at' => '2019-10-25 12:37:28',
                'route' => 'voyager.bookings.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Accounts',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2019-10-28 16:03:17',
                'updated_at' => '2019-10-28 16:03:17',
                'route' => 'voyager.accounts.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Chat Responses',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2019-11-02 12:18:33',
                'updated_at' => '2019-11-02 12:18:33',
                'route' => 'voyager.chat-responses.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}